### ISSUE TITLE
PDF viewer im branch 'Today'

### ISSUE THREAD

**Issue by bieleric** [bieleric/pbo-gigbox#6]
Aktuell liegt die PDF-Datei noch in den 'views', sollte jedoch in den 'assets' liegen. Außerdem werden Pfade noch statisch eingebunden und können nicht auf Klick aktualisiert werden.

**Comment by p-will** [comment]
PDF viewer funktioniert mit lokalen Dateien nicht. Zeitbedingter Workaround: PDF viewer genutzt, der PDFs aus dem persönlichen HTW public_html Ordner liest
